### ISSUE TITLE
feature: do not store .env file on disk

### ISSUE THREAD

**Issue by amit777** [tkalfigo/dotenvenc#12]
Hi, I don't know if it's possible with this module, but would we be able to decrypt the .env.enc file and not have any .env file stored on disk?

**Comment by amit777** [comment]
I see dotenv has a feature to parse a buffer:

```
const dotenv = require('dotenv')
const buf = Buffer.from('BASIC=basic')
const config = dotenv.parse(buf) // will return an object
console.log(typeof config, config) // object { BASIC : 'basic' }
```

Could dotenvenc return a buffer instead of writing the .env file?

**Comment by tkalfigo** [comment]
Feature was added. Enabled via additional parameter `write` passed into both `encrypt()` and `decrypt()`. Default is `true` which keeps current behavior of writing to disk. If set to `false` the methods return a buffer. 

See version 3.0.1.
