### ISSUE TITLE
Pass custom path to dotenvenc?

### ISSUE THREAD

**Issue by bdcarr** [tkalfigo/dotenvenc#2]
This is a feature request, I suppose.

The core `dotenv` library [lets you use a custom path](https://www.npmjs.com/package/dotenv#path) for your `.env`, in case it's somewhere other than the app root. Could we get support for that in `dotenvenc` too?

I ask because I'm using Mocha to run tests which are stored in different directories. Each directory (or its parent) may have its own `.env` file. Your module does traverse parent folders starting from the folder it's executed from, which is awesome, but unfortunately that doesn't help when using Mocha since the execution directory is different to the test script's directory.

I'll try to illustrate it:

    project_root/
        node_modules/
            mocha/
                bin/
                    mocha
        folder1/
            .env
        folder2/
            .env
        folder3/
            subfolder1/
                example.js
                example.spec.js
            .env

I'd like to be able to encrypt that `.env` file inside `folder3/` and decrypt it inside `example.spec.js` with `require('dotenvenc')(process.env.DOTENVENC_KEY, __dirname)`. That would cause `dotenvenc` to start looking for `.env.enc` files located in `subfolder1/`, then start checking parent folders.

The current behaviour is that `dotenvenc` starts looking inside `project_root/node_modules/mocha/bin/`, since `example.spec.js` is being executed via Mocha. It scans parent folders until reaching `project_root/` and then tells me to bugger off.

**Comment by tkalfigo** [comment]
Feature was added. Both `encrypt()` and `decrypt()` now accept optional pathname for both encrypted and decrypted files with default value `./.env.enc` and `./.env` respectively. See version 3.0.0.

**Comment by bdcarr** [comment]
Legend, thank you!
